#!/usr/bin/env bash

STEP_SIZE=${STEP_SIZE:-5}

case $BLOCK_BUTTON in
  3) xset dpms force off ;; # right click
  4) xbacklight -inc "$STEP_SIZE" ;; # scroll up
  5) xbacklight -dec "$STEP_SIZE" ;; # scroll down, decrease
esac

LIGHT=$(xbacklight -get)
echo "${LIGHT%.*}%"
